name: pendataan_desa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.0
  flutter_localizations:
    sdk: flutter 
  another_flushbar: ^1.10.29
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/pattern.jpg
    - assets/images/burung.jpeg

flutter_native_splash:
  color: "#ffffff" 
  image: assets/images/burung.jpeg
  android: true
  ios: true
  fullscreen: true
